theme: jekyll-theme-cayman
title: Disaster risk management as poverty reduction - Research Proposal
description: Using satellite data and machine learning to better target earlier assistance in climate disasters
