theme: jekyll-theme-slate
title: Disaster risk management as poverty reduction
description: Using satellite data and machine learning to target anticipatory assistance in climate disasters
markdown: kramdown
